//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naturvida20210817.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Detalle
    {
        public int Id { get; set; }
        public Nullable<int> Numero_Factura { get; set; }
        public string Codigo_Productos { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Valor_Unidad { get; set; }
    }
}
